dist: xenial
language: python

python:
    - "3.7"

install:
  - PIPENV_VERBOSITY=-1 pipenv install --dev

script:
  - pipenv run flake8 wordhunter
  - pipenv run pylint wordhunter
  - pipenv run python selftests/run.py
